#!/usr/bin/env bash
# manage files

case "$1" in
    start)
        # Start manage_my_process
        ./manage_my_process start
        ;;
    stop)
        # Stop manage_my_process
        ./manage_my_process stop
        ;;
    restart)
        # Restart manage_my_process
        ./manage_my_process restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
        ;;
esac
