#!/usr/bin/env bash
# manage files

case "$1" in
    start)
        # Check if the process is already running
        if [ -f /var/run/my_process.pid ]; then
            echo "manage_my_process is already running."
            exit 1
        fi

        # Start manage_my_process
        nohup bash -c 'while true; do echo "I am alive!" >> /tmp/my_process; sleep 2; done' > /dev/null 2>&1 &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process started."
        ;;
    stop)
        # Check if the process is not running
        if [ ! -f /var/run/my_process.pid ]; then
            echo "manage_my_process is not running."
            exit 1
        fi

        # Stop manage_my_process
        pid=$(cat /var/run/my_process.pid)
        kill $pid
        rm /var/run/my_process.pid
        echo "manage_my_process stopped."
        ;;
    restart)
        # Stop manage_my_process
        if [ -f /var/run/my_process.pid ]; then
            pid=$(cat /var/run/my_process.pid)
            kill $pid
            rm /var/run/my_process.pid
        fi

        # Start manage_my_process
        nohup bash -c 'while true; do echo "I am alive!" >> /tmp/my_process; sleep 2; done' > /dev/null 2>&1 &
        echo $! > /var/run/my_process.pid
        echo "manage_my_process restarted."
        ;;
    *)
        echo "Usage: manage_my_process {start|stop|restart}"
        exit 1
        ;;
esac

